spring.application.name=dispensa

spring.profiles.active=test

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.frontend.url=${FRONTEND_URL:http://localhost:5173}
jwt.secret=JWT_SECRET=du_r8UNfBw5PULroV5ATkZyAfMWQeYcpGeZ7MX2WpOT1e3WoSOvP08LSJ1k1fXMn
